# -*- mode: python ; coding: utf-8 -*-

from PyInstaller.utils.hooks import collect_data_files

a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=[('icon.ico', '.')] + collect_data_files('tkinterdnd2') + collect_data_files('customtkinter'),
    hiddenimports=[
        'ui_screens',
        'modpack_manager',
        'mod_jar_extractor',
        'translation_runner',
        'translation_engines',
        'file_processors',
        'review_checks',
        'hqm_parser',
        'hqm_parser.hqm_binary',
        'customtkinter',
        'tkinterdnd2',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'PIL.ImageOps',
        'google.genai',
        'deep_translator',
        'openai',
        'anthropic',
        'translation_memory',
        'translation_core',
        'patchouli_processor',
        'custom_book_processor',
        'constants',
        'state_manager',
        'requests',
        'updater',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='QuestTranslatorPro',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # cmd 콘솔 창 숨김 (GUI 모드)
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    onefile=True,
    icon='icon.ico',
)
